model_list:
  - model_name: glm-flash
    litellm_params:
      model: openai/cyankiwi/GLM-4.7-Flash-AWQ-4bit
      api_base: http://vllm-glm:8000/v1
      api_key: EMPTY

general_settings:
  master_key: "cambiaLAclave"
  database_url: "os.environ/DATABASE_URL"
