model_list:
  - model_name: qwen-max
    litellm_params:
      model: openai/Qwen/Qwen2.5-32B-Instruct-AWQ
      api_base: http://vllm-qwen32b:8000/v1
      api_key: EMPTY

general_settings:
  master_key: "cambiaLAclave"
  database_url: "os.environ/DATABASE_URL"
